Preparing update Feb20 [WIP]
lsmo-epfl/discover-curated-cofs pull request #25
Opened 2020-02-10 09:12 UTC by danieleongari

In this update we are including more COFs,
but I'm also making this discover section more similar to nanoporous_screening.

2020-02-10 11:27 UTC, danieleongari commented
Hi @ltalirz, 
I made some nice improvements, but I got some problems in the detail page. 
See my last commit:
```
not working:
1) aiida logo 
2) jsmol structure
3) graph not working with panel-v0.8
``` 
The first is probably working online but not locally with `bokeh serve`.

Can you please give them a look? 
The aiida export you have should work for testing purpose.

2020-02-10 11:32 UTC, danieleongari commented
Also, let's consider moving this repo to lsmo-epfl:
for small projects it make more sense to have just one repository, without too many fork, so that both of us can more agilely edit PRs and issues.

2020-02-12 18:45 UTC, ltalirz commented
> The aiida export you have should work for testing purpose.

You mean the one from the nanoporous pipeline? 
That doesn't seem to be working for me...

```
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/openstack/discover-sections/curated-cofs/detail/query.py", line 12, in get_group_as_dict
    group_node = qb.all()[0][0]
IndexError: list index out of range
```

> Also, let's consider moving this repo to lsmo-epfl

Fine with me - I'll do this after we've deployed it to materials cloud (since we need to update the ansible scripts in this case as well).

2020-02-12 18:48 UTC, ltalirz commented
In the meanwhile, you can try with this diff
```
diff --git a/detail/main.py b/detail/main.py
index f9d5188..1640716 100644
--- a/detail/main.py
+++ b/detail/main.py
@@ -50,21 +50,6 @@ def get_title(text, uuid=None):
     return title


-class PlainSVG(pn.pane.SVG):
-    """Drop-in replacement for pn.pane.SVG that outputs plain SVG (not base64-encoded).
-
-    Note: links encoded with xlink:href are not displayed in base64-encoded SVGs.
-    """
-
-    def _get_properties(self):
-        p = super(PlainSVG, self)._get_properties()
-        data = self._img()
-
-        if self.object is None:
-            return dict(p, text='<img></img>')
-        return dict(p, text=data)
-
-
 pn.extension()


@@ -108,7 +93,7 @@ class DetailView():

     def graph(self):
         from detail.graph import get_graph
-        column = pn.Column(PlainSVG(get_graph(self.group_dict['group'], self.group_dict)))
+        column = pn.Column(pn.pane.SVG(get_graph(self.group_dict['group'], self.group_dict)))
         column.append("CURATED-COF {}, version: {}".format(self.group_dict['cof_label'], self.group_dict['version']))
         return column
```

2020-02-13 08:49 UTC, danieleongari commented
All problems fixed!

2020-02-13 09:01 UTC, ltalirz requested changes
thanks a lot @danieleongari 

I have a few minor change requests, then good to merge

2020-02-13 09:01 UTC, ltalirz commented on .pre-commit-config.yaml
> -  - id: prospector
Could you put this back please?

It may seem like a bit of a drain from time to time, but for me as the maintainer it definitely saves time by pointing out issues that would otherwise cause bugs & time wasted debugging.

2020-02-13 09:01 UTC, ltalirz commented on .yapfignore
> +setup.py
Just to understand - why do we want to ignore this?

2020-02-13 09:01 UTC, ltalirz commented on figure/static/quantities.yml
> +  descr: Parassitic energy for carbon capture and sequestration from a coal power plant
```suggestion
  descr: Parasitic energy for carbon capture and sequestration from a coal power plant
```

2020-02-13 09:01 UTC, ltalirz commented on setup.py
> -          extras_require={
Can we put this back?

This is for developers only, no need to install this on materials cloud

2020-02-13 09:01 UTC, ltalirz commented on setup.py
> +              "pylint>=2.4.0"
usually a good idea to fix versions for the linter stuff, since they come up with new rules every now and then

2020-02-13 14:20 UTC, danieleongari commented on .yapfignore
> +setup.py
It puts all the required in one line, being complicated to read. 
I could not disable this with `#yaml: disable`

2020-02-13 15:09 UTC, ltalirz approved these changes
thanks @danieleongari !

2020-02-13 15:14 UTC, merged